import { beforeEach, describe, expect, it, vi } from "vitest";

const getServerSession = vi.fn();
const userFindUnique = vi.fn();
const accountFindFirst = vi.fn();
const postCreate = vi.fn();
const postUpdate = vi.fn();
const publishToSocial = vi.fn();

vi.mock("next-auth", () => ({ getServerSession: (...args: unknown[]) => getServerSession(...args) }));
vi.mock("@/lib/auth", () => ({ authOptions: {} }));
vi.mock("@/lib/rate-limit", () => ({
  rateLimit: () => ({ ok: true }),
  getClientIp: () => "127.0.0.1",
}));
vi.mock("@/lib/db", () => ({
  db: {
    user: { findUnique: (...args: unknown[]) => userFindUnique(...args) },
    socialAccount: { findFirst: (...args: unknown[]) => accountFindFirst(...args) },
    socialPost: {
      create: (...args: unknown[]) => postCreate(...args),
      update: (...args: unknown[]) => postUpdate(...args),
    },
  },
}));
vi.mock("@/lib/social/publish", () => ({
  publishToSocial: (...args: unknown[]) => publishToSocial(...args),
}));

const { POST } = await import("./route");

function request(videoUrl = "https://forgecut.app/api/media/jobs/job_1/attempts/token/output.mp4"): Request {
  return new Request("https://forgecut.app/api/social/post", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ socialAccountId: "account_1", videoUrl, caption: "A useful clip" }),
  });
}

beforeEach(() => {
  vi.clearAllMocks();
  process.env.NEXTAUTH_URL = "https://forgecut.app";
  getServerSession.mockResolvedValue({ user: { id: "user_1" } });
  userFindUnique.mockResolvedValue({ plan: "creator" });
  accountFindFirst.mockResolvedValue({ id: "account_1", platform: "youtube" });
  postCreate.mockResolvedValue({ id: "post_1" });
  postUpdate.mockResolvedValue({});
  publishToSocial.mockResolvedValue({ platformPostId: "platform_1" });
});

describe("POST /api/social/post", () => {
  it("blocks Free accounts before creating a post", async () => {
    userFindUnique.mockResolvedValue({ plan: "free" });
    const response = await POST(request());
    expect(response.status).toBe(403);
    expect(postCreate).not.toHaveBeenCalled();
  });

  it("accepts fenced job media generated by the current render pipeline", async () => {
    const response = await POST(request());
    expect(response.status).toBe(200);
    expect(await response.json()).toEqual({ postId: "post_1", status: "posted", platformPostId: "platform_1" });
  });

  it("continues to accept legacy owned media URLs", async () => {
    const response = await POST(request("https://forgecut.app/api/media/media/user_1/project_1/output.mp4"));
    expect(response.status).toBe(200);
  });

  it("rejects external and cross-origin media URLs before any database write", async () => {
    const response = await POST(request("https://attacker.example/api/media/jobs/job_1/output.mp4"));
    expect(response.status).toBe(400);
    expect(postCreate).not.toHaveBeenCalled();
  });
});
